# Generated by Django 4.1.5 on 2023-01-04 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='idTeacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='idClassroom',
        ),
        migrations.DeleteModel(
            name='OrderedAlumn',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
