# Generated by Django 4.1.5 on 2023-01-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('course', models.CharField(max_length=30)),
                ('evaluator', models.CharField(max_length=50)),
                ('exam_duration', models.IntegerField(default=0)),
                ('questions', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('course', models.CharField(max_length=30)),
                ('evaluator', models.CharField(max_length=50)),
                ('project_theme', models.CharField(max_length=100)),
                ('groups_numbers', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectProxy',
            fields=[
            ],
            options={
                'ordering': ['project_theme'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('administration.project',),
        ),
    ]
